name: vortex_forge
description: Flutter boilerplate generator for GetX + MVC without Mason/Get CLI.
version: 1.0.3
homepage: https://github.com/Pruthviraj36/vortex_forge
repository: https://github.com/Pruthviraj36/vortex_forge
issue_tracker: https://github.com/Pruthviraj36/vortex_forge/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8

executables:
  vortex_forge: flutter_forge
  vx: flutter_forge
